name: Run Flask Tests
on: [push, pull_request]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies into virtual env
        run: |
          python -m pip install --upgrade pip
          python3 -m venv .venv
          .venv/bin/pip install -r requirements.txt
      - name: Set Environment Variables
        run: | 
          touch .env
          echo "API_KEY = ab6c5f31aaa48f332b5ffc67168bf1b69b849442" > .env
      - name: Run Flask Server
        run: |
          .venv/bin/python3 simple_app.py &
          
      - name: Install Plugin
        run: pip install pytest-github-actions-annotate-failures
          
      - name: Tests
        run: .venv/bin/pytest 

